# Generated by Django 4.2.7 on 2025-08-02 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Users with whom this task is shared', related_name='shared_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
